### ISSUE TITLE
无法启动插件

### ISSUE THREAD

**Issue by ABKQPO** [roiiiu/nonebot-plugin-csgo-case-simulator#2]
05-07 23:55:29 [ERROR] nonebot | Failed to import "nonebot-plugin-csgo-case-simulator"
Traceback (most recent call last):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_exceptions.py", line 8, in map_exceptions
    yield
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 76, in start_tls
    raise exc
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 67, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\anyio\streams\tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\anyio\streams\tls.py", line 151, in _call_sslobject_method
    raise BrokenResourceError from exc
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\http_proxy.py", line 286, in handle_async_request
    stream = await stream.start_tls(**kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 64, in start_tls
    with map_exceptions(exc_map):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\__init__.py", line 19, in <module>
    asyncio.run(get_all_json())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\__init__.py", line 15, in get_all_json
    res = await asyncio.gather(cases.get_cases_json(), skins.get_skins_json())
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\cases.py", line 27, in get_cases_json
    return await client.get(self.cases_api)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1754, in get
    return await self.request(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError

**Comment by roiiiu** [comment]
@ABKQPO 更新了使用离线json检索数据，现在应该会在新版本中修复: 9115e4c
