### ISSUE TITLE
更新后报错没法用了

### ISSUE THREAD

**Issue by 360add** [roiiiu/nonebot-plugin-csgo-case-simulator#25]
![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/140232510/116694b6-fb68-4e57-815d-2e71a3bfad74)

**Comment by roiiiu** [comment]
> ![image](https://github.com/roiiiu/nonebot-plugin-csgo-case-simulator/assets/140232510/116694b6-fb68-4e57-815d-2e71a3bfad74)
> 

好像是字体包的问题，最近有时间我会调查一下。

**Comment by ab-Royo** [comment]
遇到了相同的问题
```

05-04 16:01:12 [SUCCESS] nonebot | OneBot V11 329***27 | [message.group.normal]: Message 155***66 from 6***11@[群:21***37] 'cases'
05-04 16:01:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot-plugin-csgo-case-simulator, lineno=21)
05-04 16:01:12 [INFO] nonebot | Matcher(type='message', module=nonebot-plugin-csgo-case-simulator, lineno=21) running complete
05-04 16:01:12 [ERROR] nonebot | Running Matcher(type='message', module=nonebot-plugin-csgo-case-simulator, lineno=21) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\__init__.py", line 30, in handle_list_cases
    cases_list_img = utils.generate_case_list_img(cases_list)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\utils.py", line 181, in generate_case_list_img
    line_height = font.getsize("A")[1] + 2
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

```

**Comment by roiiiu** [comment]
> 遇到了相同的问题
> 
> ```
> 
> 05-04 16:01:12 [SUCCESS] nonebot | OneBot V11 329***27 | [message.group.normal]: Message 155***66 from 6***11@[群:21***37] 'cases'
> 05-04 16:01:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot-plugin-csgo-case-simulator, lineno=21)
> 05-04 16:01:12 [INFO] nonebot | Matcher(type='message', module=nonebot-plugin-csgo-case-simulator, lineno=21) running complete
> 05-04 16:01:12 [ERROR] nonebot | Running Matcher(type='message', module=nonebot-plugin-csgo-case-simulator, lineno=21) failed.
> Traceback (most recent call last):
>   File "<string>", line 17, in <module>
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\__init__.py", line 334, in run
>     get_driver().run(*args, **kwargs)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
>     uvicorn.run(
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\uvicorn\main.py", line 575, in run
>     server.run()
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
>     self.run_forever()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
>     super().run_forever()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
>     self._run_once()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
>     handle._run()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
>     await _run_matcher(
> > File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
>     await matcher.run(bot, event, state, stack, dependency_cache)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
>     await self.simple_run(bot, event, state, stack, dependency_cache)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
>     await handler(
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
>     return await cast(Callable[..., Awaitable[R]], self.call)(**values)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\__init__.py", line 30, in handle_list_cases
>     cases_list_img = utils.generate_case_list_img(cases_list)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\utils.py", line 181, in generate_case_list_img
>     line_height = font.getsize("A")[1] + 2
> AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
> ```

Pillow版本问题，已修复。
