### ISSUE TITLE
开箱失败

### ISSUE THREAD

**Issue by ABKQPO** [roiiiu/nonebot-plugin-csgo-case-simulator#5]
05-10 07:07:57 [ERROR] nonebot | Running Matcher(type='message', module=nonebot-plugin-csgo-case-simulator) failed.
Traceback (most recent call last):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_exceptions.py", line 8, in map_exceptions
    yield
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 76, in start_tls
    raise exc
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 67, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\anyio\streams\tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\anyio\streams\tls.py", line 151, in _call_sslobject_method
    raise BrokenResourceError from exc
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\http_proxy.py", line 286, in handle_async_request
    stream = await stream.start_tls(**kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 64, in start_tls
    with map_exceptions(exc_map):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\__init__.py", line 85, in handle_open_crate
    image = await utils.merge_images(opened_skins)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\utils.py", line 34, in merge_images
    image_list = await asyncio.gather(*image_tasks)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\utils.py", line 109, in download_image
    response = await client.get(url)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1754, in get
    return await self.request(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError

**Comment by roiiiu** [comment]
@ABKQPO 你好，根据错误信息来看，是从cdn获取皮肤图片时发生的网络连接错误，请你检查网络环境，或者使用代理工具。

**Comment by roiiiu** [comment]
添加了代理
