### ISSUE TITLE
开箱失败

### ISSUE THREAD

**Issue by Pennsy1** [roiiiu/nonebot-plugin-csgo-case-simulator#7]
05-11 23:32:26 [ERROR] nonebot | Running Matcher(type='message', module=nonebot-plugin-csgo-case-simulator) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Program Files\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "D:\Program Files\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "D:\Program Files\Python\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "D:\Program Files\Python\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Program Files\Python\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "D:\Program Files\Python\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "D:\Program Files\Python\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "E:\文档\pip\Qbot\.venv\Lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\nonebot-plugin-csgo-case-simulator\__init__.py", line 64, in handle_open_crate
    img_base64 = await utils.img_from_url(crate["image"])
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\nonebot-plugin-csgo-case-simulator\utils.py", line 120, in img_from_url
    response = await client.get(url)
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\httpx\_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\httpx\_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 289, in handle_async_request
    stream = await stream.start_tls(**kwargs)
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\httpcore\backends\asyncio.py", line 78, in start_tls
    raise exc
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\httpcore\backends\asyncio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\anyio\streams\tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "E:\文档\pip\Qbot\.venv\Lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "D:\Program Files\Python\Lib\ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

**Comment by roiiiu** [comment]
添加了代理
