### ISSUE TITLE
插件启动失败

### ISSUE THREAD

**Issue by ab-Royo** [roiiiu/nonebot-plugin-csgo-case-simulator#9]
插件导入到nonebot2之后启动bot出现如下错误，服务器网络正常可以访问外网。对Python和nonebot还不是很了解，请问一下这个问题应该怎么解决 ovo

```python
07-28 19:23:54 [ERROR] nonebot | Failed to import "nonebot-plugin-csgo-case-simulator"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 78, in start_tls
    raise exc
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\anyio\streams\tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\anyio\streams\tls.py", line 151, in _call_sslobject_method
    raise BrokenResourceError from exc
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\_async\connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 78, in start_tls
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 241, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\__init__.py", line 25, in <module>
    asyncio.run(get_all_json())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\__init__.py", line 16, in get_all_json
    res = await asyncio.gather(
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\crates.py", line 33, in get_souvenirs_json
    return await client.get(self.souvenirs_api)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F7F468C700>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F7F468C700>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
除了以上报错，有时报错内容中还会出现`proxy.zhongpeiying.com/`

**Comment by roiiiu** [comment]
> 插件导入到nonebot2之后启动bot出现如下错误，服务器网络正常可以访问外网。对Python和nonebot还不是很了解，请问一下这个问题应该怎么解决 ovo
> 
> ```python
> 07-28 19:23:54 [ERROR] nonebot | Failed to import "nonebot-plugin-csgo-case-simulator"
> Traceback (most recent call last):
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
>     result = func(*args)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 944, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:1129)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
>     yield
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 78, in start_tls
>     raise exc
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 69, in start_tls
>     ssl_stream = await anyio.streams.tls.TLSStream.wrap(
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\anyio\streams\tls.py", line 122, in wrap
>     await wrapper._call_sslobject_method(ssl_object.do_handshake)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\anyio\streams\tls.py", line 151, in _call_sslobject_method
>     raise BrokenResourceError from exc
> anyio.BrokenResourceError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
>     yield
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
>     resp = await self._pool.handle_async_request(req)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
>     raise exc
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
>     response = await connection.handle_async_request(request)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
>     raise exc
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
>     stream = await self._connect(request)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\_async\connection.py", line 150, in _connect
>     stream = await stream.start_tls(**kwargs)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 78, in start_tls
>     raise exc
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
>     raise to_exc(exc)
> httpcore.ConnectError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<string>", line 14, in <module>
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\load.py", line 125, in load_from_toml
>     return load_all_plugins(plugins, plugin_dirs)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\load.py", line 62, in load_all_plugins
>     return manager.load_all_plugins()
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
>     return set(
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
>     filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
>     module = importlib.import_module(name)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 241, in exec_module
>     super().exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\__init__.py", line 25, in <module>
>     asyncio.run(get_all_json())
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
>     return future.result()
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\__init__.py", line 16, in get_all_json
>     res = await asyncio.gather(
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot-plugin-csgo-case-simulator\crates.py", line 33, in get_souvenirs_json
>     return await client.get(self.souvenirs_api)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_client.py", line 1757, in get
>     return await self.request(
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_client.py", line 1533, in request
>     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_client.py", line 1620, in send
>     response = await self._send_handling_auth(
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
>     response = await self._send_handling_redirects(
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
>     response = await self._send_single_request(request)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_client.py", line 1722, in _send_single_request
>     response = await transport.handle_async_request(request)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
>     resp = await self._pool.handle_async_request(req)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
>     raise mapped_exc(message) from exc
> httpx.ConnectError
> Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F7F468C700>
> Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
>     self.close()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
>     self._loop.call_soon(self._call_connection_lost, None)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
>     self._check_closed()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
>     raise RuntimeError('Event loop is closed')
> RuntimeError: Event loop is closed
> Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F7F468C700>
> Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
>     self.close()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
>     self._loop.call_soon(self._call_connection_lost, None)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
>     self._check_closed()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
>     raise RuntimeError('Event loop is closed')
> RuntimeError: Event loop is closed
> ```
> 
> 除了以上报错，有时报错内容中还会出现`proxy.zhongpeiying.com/`

图片的api都是来自一个开源仓库，不是特别稳定，还有最近腾讯对机器人政策严格，所以暂时没有更新修复。 🤔

**Comment by ab-Royo** [comment]
ooook，好吧，如果大佬有时间还是希望可以维护一下~

**Comment by roiiiu** [comment]
> ooook，好吧，如果大佬有时间还是希望可以维护一下~

临时修了一个版本，0.1.17可以使用了

**Comment by ab-Royo** [comment]
已经使用上了，好耶！
